name: Deploy Frontend with Docker Compose

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to VPS and restart Docker containers for Frontend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /home/protosedu/protosedu-prod/protosedu-frontend/webproject
            git checkout main
            git pull origin main
            docker compose down
            docker compose up --build -d
